" Theme settings for Vim and Gvim

" disable visual alert for errors
set noerrorbells visualbell t_vb=
if has('autocmd')
  autocmd GUIEnter * set visualbell t_vb=
endif

if has('mouse')
  set mouse=a " enable mouse mode (scrolling, selection, etc)
end

" Disable CTRL-A on tmux or on screen
if $TERM =~ 'screen'
  nnoremap <C-a> <nop>
  nnoremap <leader><C-a> <C-a>
endif

if &term =~ '^screen'
  if has('mouse_sgr')
    set ttymouse=sgr
  else
    " tmux knows the extended mouse mode
    silent! set ttymouse=xterm2
  endif

  " provide appropriate key sequences when xterm-keys is enabled in tmux
  set t_kN=^[[6;*~
  set t_kP=^[[5;*~
endif

" enables 256 color in vim, place BEFORE setting the colorscheme
set term=xterm-256color
set t_Co=256 " iTerm2 256 color mode for Airline highlight
set t_AB=[48;5;%dm
set t_AF=[38;5;%dm

" Change cursor shape between insert and normal mode in iTerm2.app
if $TERM_PROGRAM =~ "iTerm.app"
  if exists($TMUX)
    set term=screen-256color
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
    if v:version >= 800
      let &t_SR = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=2\x7\<Esc>\\"
    endif
  else " tmux not running
    let &t_SI = "\<Esc>]50;CursorShape=1\x7" " Vertical bar in insert mode
    let &t_EI = "\<Esc>]50;CursorShape=0\x7" " Block in normal mode
    if v:version >= 800
      let &t_SR = "\<Esc>]50;CursorShape=2\x7" " Underline in replace mode
    endif
  endif
else
  " Terminal settings
endif

" Color theme for GUI vs CLI Vim
if has("gui_running") " MacVim
  set gfn=Hack:h13 " columns=80 lines=40
else " Vim
  " Bae16-Dark theme, NOTE: requires base16-shell to be setup
  " let g:base16colorspace=256
  " colorscheme base16-default-dark
endif

set background=dark
" colorscheme tender
colorscheme gruvbox

" NOTE: must be after setting colorscheme, otherwise may get overridden by colorscheme
set colorcolumn=81
highlight ColorColumn cterm=NONE ctermbg=black gui=NONE guibg=black
" highlight ColorColumn cterm=NONE ctermbg=185 guibg=#c9d05c
highlight Visual term=standout cterm=bold ctermfg=235 ctermbg=185 gui=bold guifg=#282828 guibg=#c9d05c
highlight Search term=standout cterm=bold ctermfg=235 ctermbg=185 gui=bold guifg=#282828 guibg=#c9d05c
highlight QuickFixLine term=NONE cterm=NONE gui=NONE

" TODO: fix buffer display corrupted after switching iTerm tab
" dim columns past 80 chars using highlight, NOTE: comment out any ColorColumn settings
" execute "set colorcolumn=" . join(range(81,335), ',')

" ~/.vimrc_background should be generated by base16-shell
" if filereadable(expand("~/.vimrc_background"))
"   let base16colorspace=256
"   source ~/.vimrc_background
" endif

" dynamically matches theme to iTerm's current
" if filereadable(expand("~/.vimrc_background"))
"   let base16colorspace=256
"   source ~/.vimrc_background
" endif

